### ISSUE TITLE
Not working on new Microsoft Edge

### ISSUE THREAD

**Issue by tarushvkodes** [ScratchFormat/scratchformat#1]
none of the things are working

**Comment by petabyt** [comment]
@03172008 Could you be more specific? Browser info, screenshot

**Comment by daniel4-scratch** [comment]
I don't see anything wrong?

**Comment by tarushvkodes** [comment]
If i highlight the text, it will not do anything if I  click bold, italic, or anything.

**Comment by tarushvkodes** [comment]
Microsoft Edge | 83.0.478.50 (Official build) (64-bit)
Operating system | Windows 10 OS Version 2004 (Build 19041.329)

**Comment by tarushvkodes** [comment]
I use the new MS edge, and because it is chromium based I downloaded scratchformat.

**Comment by petabyt** [comment]
I'm not sure about Microsoft Edge. I run Debian, but I can boot into Windows to test it later.

**Comment by tarushvkodes** [comment]
not the old one, https://www.microsoft.com/en-us/edge

**Comment by petabyt** [comment]
Yeah, Microsoft forked chromium.

**Comment by tarushvkodes** [comment]
yea ik so it should not be the browser problem right?

**Comment by petabyt** [comment]
Well, it works fine on Chromium (Version 80.0.3987.162 (Developer Build) built on Debian 10.3, running on Debian 10.4 (64-bit)) on my end, so I am not sure.

Do you see any errors in the developers console?

**Comment by petabyt** [comment]
Running latest version of Microsoft Edge (Version 83.0.478.50 (Official build) (64-bit)) works good on my end.
NOT supported Microsoft Edge (doesn't support chrome script injection)

**Comment by petabyt** [comment]
Try the latest version.

**Comment by tarushvkodes** [comment]
ok

**Comment by tarushvkodes** [comment]
I'm using Version 83.0.478.50 (Official build) (64-bit).

**Comment by petabyt** [comment]
Still not working?

**Comment by tarushvkodes** [comment]
Yea it's still not working, let me try reinstalling the extention

**Comment by petabyt** [comment]
Oh, you installed from Chrome web store?

**Comment by petabyt** [comment]
I am running the latest version via Edge developer mode.

**Comment by tarushvkodes** [comment]
yes, am I supposed to install it elsewhere?

**Comment by tarushvkodes** [comment]
How do you enable edge developer mode?

**Comment by petabyt** [comment]
Chrome web store doesn't have latest version yet. Try downloading the repo as ZIP,
go to edge://extensions, turn on developer mode, and try loading the extension zip.

**Comment by tarushvkodes** [comment]
ok

**Comment by tarushvkodes** [comment]
![image](https://user-images.githubusercontent.com/47307733/85067047-0a002a00-b17e-11ea-9736-1a45c981e41c.png)

**Comment by tarushvkodes** [comment]
what do I do now @pufflegamerz

**Comment by petabyt** [comment]
I can't reproduce.

**Comment by petabyt** [comment]
Did you unzip the file, then "Load as unpacked"?

**Comment by tarushvkodes** [comment]
Yes. It is still not working. Whenever I highlight the text, then press any of the buttons, on any page, it just exits out of the box and does not do anything.

**Comment by petabyt** [comment]
Does manually typing in `[b]test[/b]` work?

**Comment by tarushvkodes** [comment]
I have not tried that yet. I will try that now.

**Comment by tarushvkodes** [comment]
Yes. bold does work if you input it manually.

**Comment by tarushvkodes** [comment]
ScratchFormat still does not do anything and does not insert those tags either.

**Comment by petabyt** [comment]
https://youtu.be/X2oy3oIkLKI

**Comment by petabyt** [comment]
That is what you are doing correct?

**Comment by petabyt** [comment]
Do you have any other extensions?

**Comment by tarushvkodes** [comment]
no, so far I have been highlighting the text I want bold, I will try that.

**Comment by tarushvkodes** [comment]
> Do you have any other extensions?

yes.

**Comment by petabyt** [comment]
Does disabling them do anything?

**Comment by tarushvkodes** [comment]
no, disabling them does nothing.
also, even when I do the thing mentioned in the video clicking them without highlighting anything does not work. It does the same thing as before.

**Comment by petabyt** [comment]
What type of Scratch page are you on?

**Comment by tarushvkodes** [comment]
I am on my profile page just like in the video

**Comment by petabyt** [comment]
Could you give me the page? I'm not sure if it is different

**Comment by petabyt** [comment]
Does it work on my profile?
https://scratch.mit.edu/users/pufflegamerz/

**Comment by scratchusernamemrtbts** [comment]
> https://youtu.be/X2oy3oIkLKI

i cannot watch the video

**Comment by scratchusernamemrtbts** [comment]
it works fine for me
i'm using mac

**Comment by petabyt** [comment]
> > https://youtu.be/X2oy3oIkLKI
> 
> i cannot watch the video

I deleted it after a while.

**Comment by scratchusernamemrtbts** [comment]
> > > https://youtu.be/X2oy3oIkLKI
> 
> > 
> 
> > i cannot watch the video
> 
> 
> 
> I deleted it after a while.

Oh

**Comment by petabyt** [comment]
@03172008 Was the issue ever fixed?

**Comment by tarushvkodes** [comment]
Nope
________________________________

**Comment by petabyt** [comment]
Using the recently updated version?
