### ISSUE TITLE
Replacing SFCode with Markdown

### ISSUE THREAD

**Issue by petabyt** [ScratchFormat/scratchformat#10]
Since SF's launch in 2017, it has always used a modified version of BBCode called SFCode.
I am proposing to not implement alongside, but replace SFCode with Markdown.

SFCode:
Pros: Keeping it the same since launch for old comments to work. Very flexible, color support, fun to mess with
Cons: Hard to read, messy
Markdown:
Pros: Used everywhere in chat systems, clean, readable with and without extension.
Cons: Old comments will be broken.

**Comment by petabyt** [comment]
Please let me know if you think this is a good idea and what else I could consider.

**Comment by daniel4-scratch** [comment]
Use the [Cheat Sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet), to get commands, and yes I think this is a good idea.

**Comment by petabyt** [comment]
We can't completely replace it. But bold and italics now already use markdown instead of SFCode. But the old style still works.
