### ISSUE TITLE
Nothing works on 2.0 pages

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#13]
The `?` **button won't show** the box on profile pages and 2.0 pages

**Comment by petabyt** [comment]
It works for me on Firefox and Chromium. What browser/version are you using? I know it is buggy on 3.0 pages.

**Comment by daniel4-scratch** [comment]
Version 85.0.4183.83 (Official Build) (64-bit) Chrome

**Comment by petabyt** [comment]
Sorry, I meant Browser and version of ScratchFormat.

**Comment by daniel4-scratch** [comment]
2.2 / chrome

**Comment by petabyt** [comment]
Any console errors?

**Comment by daniel4-scratch** [comment]
How do I view that? If it's inspect, I can't

**Comment by petabyt** [comment]
Yeah, they are in the developers console.

**Comment by daniel4-scratch** [comment]
Ok, I have problems then, the inspect is disabled.

**Comment by petabyt** [comment]
Were you able to see errors?

**Comment by daniel4-scratch** [comment]
No, I’ll check

**Comment by daniel4-scratch** [comment]
I'm trying to re-install ScratchFormat and I get this message:
```
Could not install package: 'COULD_NOT_GET_TEMP_DIRECTORY'
```

**Comment by daniel4-scratch** [comment]
Yeah, I can’t download ScratchFormat

**Comment by petabyt** [comment]
That is not a ScratchFormat message.

**Comment by petabyt** [comment]
A quick search shows this:
https://support.google.com/chrome/thread/33767309?hl=en
From an extension called "Browsec"

**Comment by daniel4-scratch** [comment]
Ok

**Comment by petabyt** [comment]
The latest version is working good on my Windows 10 Chrome installation.

**Comment by daniel4-scratch** [comment]
Ok, I was able to download scratchformat now

**Comment by daniel4-scratch** [comment]
I see no errors

**Comment by daniel4-scratch** [comment]
Not even the buttons work.

**Comment by petabyt** [comment]
That would be a problem on your end... It has worked perfectly on Firefox, Chrome, Chromium for me.
Can you get any console errors when you click the buttons?
Try disabling all your extensions except ScratchFormat.

**Comment by daniel4-scratch** [comment]
Wait, I figured it out! ScratchMoji was interfering with ScratchFormat so I have removed ScratchMoji, and it is back to normal!

**Comment by daniel4-scratch** [comment]
but the issues button doesn't work :[

**Comment by petabyt** [comment]
Thanks for help. I will definitely look into that.

**Comment by petabyt** [comment]
I tried ScratchMoji again, it all works.

**Comment by petabyt** [comment]
Help button also works for me too.

**Comment by daniel4-scratch** [comment]
hmm
