### ISSUE TITLE
Idea: Formatting in the mailbox

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#15]
When someone replies, scratch shows you in your mailbox and if they use scratchformat it will show the code, Add formatting to the mailbox

**Comment by daniel4-scratch** [comment]
#16 Pull request

**Comment by petabyt** [comment]
Nice idea, but I don't think that PR would do the trick. Did you test it?

**Comment by daniel4-scratch** [comment]
only problem is how do i test, I am on mac and i can't edit specific files.

**Comment by petabyt** [comment]
You would have to git clone or download the extension, and edit the files from there, then load the extension in manually with your web browser.

**Comment by daniel4-scratch** [comment]
Ok

**Comment by petabyt** [comment]
![Screenshot at 2020-09-16 12-54-44](https://user-images.githubusercontent.com/32369330/93368361-e485c980-f81b-11ea-9dab-74f8e0c3891c.png)

**Comment by petabyt** [comment]
Wasn't too hard.

**Comment by daniel4-scratch** [comment]
I see Lenny face. But it works fine then?

**Comment by petabyt** [comment]
Yes. You can see the formatted comments.

**Comment by daniel4-scratch** [comment]
will this be added into SF? Just asking.

**Comment by petabyt** [comment]
Yes. I just pushed the commit. https://github.com/ScratchFormat/ScratchFormat2/commit/019090565ad5ea89aeaa944899c962c8fa8cd0e2

**Comment by daniel4-scratch** [comment]
Ok

**Comment by daniel4-scratch** [comment]
![Screen Shot 2021-06-06 at 8 55 14 pm](https://user-images.githubusercontent.com/65277548/120921906-867e7680-c709-11eb-922c-a1e114c71e1e.png)
It's not formating with the latest version of SF
