### ISSUE TITLE
Idea: Formatting in info slots

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#19]
Add the formatting into about slots, like profiles, projects and studios.
_Do you like the idea?_

**Comment by petabyt** [comment]
I'm not sure if it would be possible or practical. Like adding custom Unicode fonts and centering text?

**Comment by daniel4-scratch** [comment]
How? I’m a little confused

**Comment by petabyt** [comment]
The about box is a textarea, so you can't edit it.
And, I don't think anybody would want to make their about me have a bunch of formatting.

**Comment by daniel4-scratch** [comment]
Ok, but when you are logged out and can't edit then you can format it.

**Comment by petabyt** [comment]
I just do not think it would be useful.
