### ISSUE TITLE
Release 2.3

### ISSUE THREAD

**Issue by petabyt** [ScratchFormat/scratchformat#22]
Changes:
Icon click feedback
Popup navigation bar

TODO:

**Comment by daniel4-scratch** [comment]
What about the new nav bar on the pop up?

**Comment by daniel4-scratch** [comment]
Umm... didn't we add the formatting in the mailbox?

**Comment by petabyt** [comment]
I think I added that in the latest release. I can't remember.

**Comment by daniel4-scratch** [comment]
Browse this link on chrome it has all the files on scratchformat. It has all the latest files when you uploaded it to the chrome store.

`chrome-extension://fklhbhcbpnkiifblkhoioddoadlknecl/`
Eg:
`chrome-extension://fklhbhcbpnkiifblkhoioddoadlknecl/manifest.json`

**Comment by petabyt** [comment]
The extension ID is local, only on your machine. I have it loaded in on file anyway though.

**Comment by petabyt** [comment]
Looking at the release commits since 2.2 was made, it was added after 2.2

**Comment by petabyt** [comment]
Actually, shouldn't this go in a project board?
