### ISSUE TITLE
Happy 3 year Birthday to Scratchformat!

### ISSUE THREAD

**Issue by petabyt** [ScratchFormat/scratchformat#24]
https://github.com/pufflegamerz/ScratchFormat/commit/1d2376961e55e05b645ad72762f5d28a3a67e03e
🎉

**Comment by daniel4-scratch** [comment]
🥳 🎉  Happy b'day to scratchformat

**Comment by petabyt** [comment]
![Screenshot at 2020-12-08 20-25-02](https://user-images.githubusercontent.com/32369330/101561538-83d9d900-3993-11eb-9663-67f9a530d720.png)

Hmm. I'm confused. Maybe 4 years?

**Comment by daniel4-scratch** [comment]
Waa?

**Comment by petabyt** [comment]
Strange. I didn't even buy a Chrome Store account until December 1st, 2017.

**Comment by petabyt** [comment]
The real start date was Nov 26 2017. 4 days before extension advertising was banned :(
