### ISSUE TITLE
Small box for nav bar

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#25]
**Describe the bug**
The `popup.html` box is too short for the new nav bar it is messy
*What does this bug do? How do you recreate it?*
Just open the `popup.html` in mini mode on version 2.3

**Screenshots**
![Screen Shot 2020-12-09 at 5 59 50 pm](https://user-images.githubusercontent.com/65277548/101596230-d1fce400-3a48-11eb-9ff4-f803cbc77c87.png)

**Comment by petabyt** [comment]
I did that change on Firefox and it worked perfectly. But I guess not on chrome.
