### ISSUE TITLE
Add SF to ScratchAddons?

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#27]
Maybe when Scratch Format is bug free for a month you could ask to add SF on SA.

But its your choice! You may not want to

**Comment by petabyt** [comment]
That would make it too centralized.

**Comment by petabyt** [comment]
I like decentralization. Same reason I'm not implementing an emoji feature. I would tell people to install https://chrome.google.com/webstore/detail/scratchmoji/mnbldfncnodnfpmhblecpfidlckiiiad?hl=en
