### ISSUE TITLE
State of ScratchFormat 2021

### ISSUE THREAD

**Issue by petabyt** [ScratchFormat/scratchformat#29]
When isOnline, ScratchMoji, and maybe a few others were popular, I thought I would follow the trend and make my own
extension. I eventually thought of making a formatting extension, and have been slowly maintaining it ever since.

There isn't much to the extension to add at this point. Stability and bug fixes are the only updates that will come in the next
few years. Contributors are welcome.

SF Contributors:
@Daniel4-Scratch
@petabyt

**Comment by petabyt** [comment]
Currently have 550 users...

**Comment by daniel4-scratch** [comment]
> Currently have 550 users...

Is that good or bad? Well better than nothing.

**Comment by petabyt** [comment]
Well, it's 500 more than I would have expected in 2017.
