### ISSUE TITLE
Format doesn't work in mailbox

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#31]
**Describe the bug**
The formatting doesn't work in the mailbox
*What does this bug do? How do you recreate it?*
If some one has commented on your profile in sf tags, open the mail box and go to that comment and it's not formatted
**Screenshots**
![Screen Shot 2021-06-06 at 8 55 14 pm](https://user-images.githubusercontent.com/65277548/120922003-0efd1700-c70a-11eb-97e7-b4e0be0a2c2d.png)

**Console Errors? (Ctrl+Shift+I)**
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 27451134
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. comments
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. curators
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. polyfill.min.js:6:8768
onmozfullscreenchange is deprecated. polyfill.min.js:6:8768
onmozfullscreenerror is deprecated. polyfill.min.js:6:8768

**Comment by petabyt** [comment]
I'm using the latest release, on Firefox, and it's working fine.

**Comment by petabyt** [comment]
Perhaps https://github.com/ScratchAddons/ScratchAddons has broken it?

**Comment by daniel4-scratch** [comment]
I disabled it off and it still didn’t

**Comment by petabyt** [comment]
Any other extensions? What browser?

**Comment by daniel4-scratch** [comment]
Latest version of Firefox, I disabled them all and still no go

**Comment by petabyt** [comment]
Are you using the latest one from source or the latest from Firefox store?

**Comment by daniel4-scratch** [comment]
I'll re-install and check

nup
![Screen Shot 2021-06-10 at 6 03 40 pm](https://user-images.githubusercontent.com/65277548/121488192-327bd680-ca16-11eb-9831-aff985f1de31.png)

**Comment by petabyt** [comment]
> Are you using the latest one from source or the latest from Firefox store?

Which one?

**Comment by daniel4-scratch** [comment]
Firefox: 89.0 ScratchFormat: 24.0

**Comment by petabyt** [comment]
Okay, I'm assuming you are using the latest from Firefox store. I've tried that and the latest from source, and it's still working fine.
I've also tested it in Chrome, and it's working fine.

Are you 100% there are no errors in the console?
Are you 100% there are no other extensions interfering with it?

From what I see, It seems like SF isn't even working at all. Maybe `https://scratch.mit.edu/messages*` isn't working here?

**Comment by petabyt** [comment]
@Daniel4-Scratch

**Comment by petabyt** [comment]
I've been able to reproduce this when I installed SF more than once. This should fix it:
https://github.com/ScratchFormat/scratchformat/commit/1ccdad46b4fa80e9dd668882a35a557e7b2705eb

**Comment by daniel4-scratch** [comment]
It works know with the new release.
<sup> Sorry for not responding in a while. I took a break from programing
