### ISSUE TITLE
Message box backdrop is broken

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#33]
**Describe the bug**
*What does this bug do? How do you recreate it?*
The blue transparent backdrop doesn't cover where the user has the paged scrolled at.  Instead the blue backdrop shows at the top of the screen

**Screenshots**

https://user-images.githubusercontent.com/65277548/123728829-50cb4880-d8d7-11eb-8349-f081c5e940bc.mp4

**Console Errors? (Ctrl+Shift+I)**

*Console errors tell you if somthing has gone wrong or any code. Open it up by using Ctrl+Shift+I*
![Screen Shot 2021-06-29 at 12 43 01 pm](https://user-images.githubusercontent.com/65277548/123728972-8bcd7c00-d8d7-11eb-8ad9-4173c04ab5e5.png)

**Comment by petabyt** [comment]
How did you get the 3.0 style on the profile page?
On my end, I get the 2.0 style, and it works fine.

**Comment by petabyt** [comment]
Is this a Scratch bug? Try clicking report on a comment and see if it does the same thing.

**Comment by daniel4-scratch** [comment]
oh oops i have scratchaddons on. but the same thing still happens with it off

**Comment by petabyt** [comment]
> Is this a Scratch bug? Try clicking report on a comment and see if it does the same thing.

?

**Comment by daniel4-scratch** [comment]
I think you quoted your self

**Comment by petabyt** [comment]
Yes, you didn't answer it.

**Comment by daniel4-scratch** [comment]
it does the same thing

**Comment by petabyt** [comment]
So it's a Scratch bug, not a SF bug.
