### ISSUE TITLE
Make normal message for other people

### ISSUE THREAD

**Issue by Miala-python** [ScratchFormat/scratchformat#37]
Can-we make a database ?
Because my idea is that
- When I post a message '[i]test[/i] test' ScratchFormat post 'test test' on scratch and save the message '[i]test[/i] test' in the database.
- When I look a message: ScratchFormat search the message in the database. If he has found he show the message of the database, else he show the message of scratch.

_Sorry, I don't speak English very well._

**Comment by petabyt** [comment]
That would over-complicate things a ton. Me or somebody else would  
have to maintain a server 24/7, and if the server ever goes down, the  
entire extension would be useless.  

If you want to try it, go ahead. I'd be interested to see how it would work  
out, maybe it would be better than the this one.

Also, note that the original SFCode italics format `[i]foo[/i]` has been  
deprecated in favor of markdown. `*foo*`

**Comment by Miala-python** [comment]
> If you want to try it, go ahead. 
> I'd be interested to see how it would work out, maybe it would be better than the this one.

I can't because I not program very well in html, js, PHP and MySQL and I don't know how I can have a free server...
I don't know how to make an browser extension to...

**Comment by Miala-python** [comment]
#36

**Comment by Miala-python** [comment]
#36 / #7
