### ISSUE TITLE
Emoji idea

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#39]
I stole this idea from scratch addons.

This will make user find scratch emojis more easier. By putting a button near the textarea. When clicking the button a drop down of emojis is show and when click on emoji, it will type the emoji tag into the textarea. If we could some how implement this into the extension.
![Screen Shot 2021-11-06 at 7 18 39 pm](https://user-images.githubusercontent.com/65277548/140603165-cda250d6-f0d1-4214-83f7-752de479274d.png)

I think this would be kinda usefull. But i don't know how to add it into the extension, you are the master mind and it is your decision

[Live example](https://emoji-test-sf.glitch.me/)
[Source Code](https://glitch.com/edit/#!/emoji-test-sf)

<details><summary>New image concept</summary><dropdown>
<img src="https://user-images.githubusercontent.com/65277548/140603846-14c07f63-9a45-4f1f-9f66-8d9017b7587c.png">. 
<br>
The logo looks quit small on firefox in the nav bar, this is just an idea

</dropdown></details>

**Comment by Daniel4-Scratch** [comment]
working on pull request checking if it works... probably not #40

**Comment by petabyt** [comment]
This is something that https://github.com/Sheshank-s/ScratchMoji was good at.  
The only issue is that the previous image server is dead, so all of the images are blank.

I've pretty much quit maintaining Scratchformat, as well as being a part of the Scratch  
community. I doubt I'll be adding anything to this anytime soon, if at all.
