### ISSUE TITLE
new feature request.

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [ScratchFormat/scratchformat#4]
it would be very useful if i colud write those font in my profile about me and what i'm working on section.
and i'm not sure how do you make the big scratch cat in the picture here
![ภาพ](https://user-images.githubusercontent.com/66320961/85935910-e8423800-b91f-11ea-8774-0b3e329a7368.png)
- [x] tell me how to make the cat
- [x] add feature to write in about me and what i'm working on
- [x] fix it to work with 3.0 project comment

**Comment by scratchusernamemrtbts** [comment]
and there is another issue i cannot use it when commenting on project but i can use it when commenting on a profile

**Comment by daniel4-scratch** [comment]
The cat is an image, that was from the 1.0 version but version 2.1 doesn't have it yet

**Comment by scratchusernamemrtbts** [comment]
> The cat is an image, that was from the 1.0 version but version 2.1 doesn't have it yet

oh, thanks

**Comment by daniel4-scratch** [comment]
#oh, thanks

No problem

**Comment by petabyt** [comment]
Where did you get that image? I'm unsure about adding images. It would be a simple addition, but they could be abused. I thought it was best to it alone, as they have no practical use other than for messing around.

**Comment by petabyt** [comment]
"add feature to write in about me and what i'm working on"
This was never intended to be added, as people without the extension would see unformatted nonsense. It was an idea
from the past.

**Comment by petabyt** [comment]
"fix it to work with 3.0 project comment"
Some people have had issues with it, but I have never been able to  
figure out why other than assuming it was a problem with their browser.

**Comment by petabyt** [comment]
Custom fonts as in web fonts would be certainly possible.

**Comment by scratchusernamemrtbts** [comment]
> "fix it to work with 3.0 project comment"
> 
> Some people have had issues with it, but I have never been able to  
> 
> figure out why other than assuming it was a problem with their browser.

It works in comment but not in reply

I’m using firefox in Mac

**Comment by scratchusernamemrtbts** [comment]
> "add feature to write in about me and what i'm working on"
> 
> This was never intended to be added, as people without the extension would see unformatted nonsense. It was an idea
> 
> from the past.

I figured out how to make that. I just make a repository on github and tell them to got to my link

**Comment by scratchusernamemrtbts** [comment]
> Where did you get that image? I'm unsure about adding images. It would be a simple addition, but they could be abused. I thought it was best to it alone, as they have no practical use other than for messing around.

Is in the preview in Firefox add on website where I download it

**Comment by petabyt** [comment]
> > Where did you get that image? I'm unsure about adding images. It would be a simple addition, but they could be abused. I thought it was best to it alone, as they have no practical use other than for messing around.
> 
> Is in the preview in Firefox add on website where I download it

I do not intend on adding images not because they are difficult to implement, but because they could be abused.
