### ISSUE TITLE
The code format doesn't work on 3.0 pages

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#5]
**Describe the bug**
The code format doesn't work on 3.0 pages
**Some Screenshots**
![Screen Shot 2020-06-28 at 6 01 05 pm](https://user-images.githubusercontent.com/65277548/85941922-57904a00-b969-11ea-80dc-5b8221032e9d.png)
![Screen Shot 2020-06-28 at 6 01 45 pm](https://user-images.githubusercontent.com/65277548/85941933-70006480-b969-11ea-8d51-49a9e2620826.png)

**Comment by petabyt** [comment]
It appears to be working fine for me.

**Comment by daniel4-scratch** [comment]
> It appears to be working fine for me.

What Browser are you using?

**Comment by petabyt** [comment]
Chromium on Debian.

**Comment by petabyt** [comment]
What is your browser? I recently found that I was using a feature that was unimplemented in Firefox a few months ago.

**Comment by daniel4-scratch** [comment]
My browser is chrome

**Comment by petabyt** [comment]
And this is using the latest release from the Chrome web store?

**Comment by daniel4-scratch** [comment]
Wait, it is working now, just a fluke of it not working.
