### ISSUE TITLE
New Logo idea

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#6]
Just thinking if the logo should have an update with the new 3.0 style:
![Screen_Shot_2020-06-30_at_5-removebg-preview](https://user-images.githubusercontent.com/65277548/86097988-da93da80-baf8-11ea-82cf-daed4db9d1d7.png)

**Comment by petabyt** [comment]
That looks good. I'll be glad to get a new logo.

**Comment by daniel4-scratch** [comment]
> That looks good. I'll be glad to get a new logo.

You should make a new one!

**Comment by petabyt** [comment]
That one looks good.

**Comment by daniel4-scratch** [comment]
Thanks :)

**Comment by petabyt** [comment]
I can put this in the next release, any changes you want to make before that? I think I need it in size 400x400 px.

**Comment by daniel4-scratch** [comment]
Idk how to change the img size, you have a crack

**Comment by petabyt** [comment]
What program did you use to make it?

**Comment by daniel4-scratch** [comment]
I got the pen from [remixicon.com](https://Remixicon.com). S logo from scratch. And the program was......... ᵗʰᵉ ˢᶜʳᵃᵗᶜʰ ᵉᵈᶦᵗᵒʳ
edit: [Remove.bg](remove.bg) for adding no background to it

**Comment by daniel4-scratch** [comment]
Here it is square 800x800
![](http://u.cubeupload.com/DanielBanana4/2791C8F14F6949A4A5BD.png)
I think

**Comment by petabyt** [comment]
It's a bit fuzzy. I used http://drawings.google.com/ for the current logo, you can export high resolution pictures there.

**Comment by daniel4-scratch** [comment]
Ok

**Comment by daniel4-scratch** [comment]
> It's a bit fuzzy

But once it is small you will hardly see it

**Comment by petabyt** [comment]
It would be better in XML.

**Comment by Daniel4-Scratch** [comment]
![Scratch Format Logo](https://user-images.githubusercontent.com/65277548/88894185-d63f1680-d28a-11ea-99cf-f412433b134e.png)

**Comment by daniel4-scratch** [comment]
![Scratch Format Logo (1)](https://user-images.githubusercontent.com/65277548/88894944-fde2ae80-d28b-11ea-86e4-a42c11d21f53.png)

**Comment by daniel4-scratch** [comment]
Are you still using github because it said you stoped using it so does that mean you will not continue scratch format

**Comment by petabyt** [comment]
I never said I would stop using Github. I did say I would stop using Github pages for my personal website

**Comment by daniel4-scratch** [comment]
oh, ok

**Comment by petabyt** [comment]
![logo (2)](https://user-images.githubusercontent.com/32369330/91204922-bad0fb00-e6d2-11ea-8b6c-80675f438d15.png)

**Comment by petabyt** [comment]
My final edits to resolution.

**Comment by petabyt** [comment]
@Daniel4-Scratch We are now using your new logo design. Thanks. This will now be closed.

**Comment by daniel4-scratch** [comment]
Thanks!
