### ISSUE TITLE
if other people don't use it they will see funny text

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [ScratchFormat/scratchformat#7]
i open 2 window one is safari with no extension instaled and firefox with the extension
is there a way to make other people that don't use the extension see the rich text
<img width="2560" alt="ภาพหน้าจอ 2563-07-15 เวลา 20 23 17" src="https://user-images.githubusercontent.com/66320961/87550254-10c88100-c6d9-11ea-96e8-36518f779ddf.png">

**Comment by daniel4-scratch** [comment]
There is no real way to get rid of it, it is there for scratch format to under stand

**Comment by petabyt** [comment]
Unparsed BBCode is pretty unreadable, and a solution I proposed was to use Markdown. It looks a lot cleaner, but it would probably have to be implemented alongside BBcode, as that is what the extension always used since 2017.

**Comment by petabyt** [comment]
And @Daniel4-Scratch is right, there is no possibility that this would be possible.
